# Generated by Django 5.2 on 2025-05-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_from_me', models.BooleanField(default=False)),
                ('message_type', models.CharField(default='text', max_length=20)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
