# Generated by Django 5.2 on 2025-05-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptMesage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prompt Message',
                'verbose_name_plural': 'Prompt Messages',
            },
        ),
    ]
