# Generated by Django 5.2 on 2025-05-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.TimeField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prompt Message',
                'verbose_name_plural': 'Prompt Messages',
            },
        ),
        migrations.DeleteModel(
            name='PromptMesage',
        ),
    ]
