# Generated by Django 5.2 on 2025-05-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('nameShort', models.CharField(max_length=255, unique=True)),
                ('typeDocument', models.CharField(max_length=255)),
                ('numberDocument', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('district', models.CharField(max_length=255)),
                ('managementObservations', models.TextField(null=True)),
                ('cellphone', models.CharField(max_length=255, null=True)),
                ('nameCompany', models.CharField(max_length=255, null=True)),
                ('adressSecondary', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DateClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('observations', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_client', to='clients.client')),
            ],
        ),
    ]
