# Generated by Django 5.2 on 2025-05-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='nameShort',
            field=models.CharField(max_length=255),
        ),
    ]
