# Generated by Django 5.2 on 2025-05-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_address_alter_client_nameshort'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='billingDate',
            field=models.IntegerField(default=1, help_text='Day of the month for billing'),
            preserve_default=False,
        ),
    ]
