# Generated by Django 5.2 on 2025-05-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_active_client_billingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='billingDate',
            field=models.IntegerField(help_text='Day of the month for billing', null=True),
        ),
        migrations.DeleteModel(
            name='DateClient',
        ),
    ]
